library(dplyr)
library(lubridate)

a<-read.table("household_power_consumption.txt",sep = ";",header = TRUE)
b<-filter(a,Date=="1/2/2007"|Date=="2/2/2007")
x<-dmy_hms(paste(a$Date,a$Time))
png("plot4.png",width = 480,height = 480)
par(mfcol=c(2,2))
plot(x,as.numeric(paste(b$Global_active_power)),type = "l",ylab = "Global Active Power (kilowatts)",xlab = "")
plot(x,as.numeric(paste(b$Sub_metering_1)),type = "l",xlab = "",ylab = "Energy sub metering")
lines(x,as.numeric(paste(b$Sub_metering_2)),col = "red")
lines(x,as.numeric(paste(b$Sub_metering_3)),col = "blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),pch = "-",col = c("black","red","blue"))
plot(x,as.numeric(paste(b$Voltage)),ylab = "Voltage",xlab = "datetime",type = "l")
plot(x,as.numeric(paste(b$Global_reactive_power)),ylab = "Global_reactive_power",xlab = "datetime",type = "l")
dev.off()